/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlUsuario;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import modelo.usuario;

/**
 *
 * @author Vale
 */
public class VistaUsuarioC extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuarioConsulta
     */
    
    LinkedList<usuario> listaUsuarios;
    public VistaUsuarioC() {
        initComponents();
        listaUsuarios= new LinkedList<>();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Usuario:");

        jLabel2.setText("Ingresar ID del usuario:");

        jTextField1.setText("jTextField1");

        jButton1.setText("Buscar Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Buscar Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       //String busqueda= jTextField1.getText();
        ControlUsuario objcu= new ControlUsuario();
        int ncol;
        Object[] fila;
        
       // if (busqueda.equals("")){
            listaUsuarios = objcu.consultarUsuarios();
            
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable2.setModel(modelo);
            
            modelo.addColumn("primer nombre");
            modelo.addColumn("segundo nombre");
            modelo.addColumn("primer apellido");
            modelo.addColumn("segundo apellido");
            modelo.addColumn("foto perfil");
            modelo.addColumn("correo");
            modelo.addColumn("contraseña");
            modelo.addColumn("Estado bloqueo");
            modelo.addColumn("rol");
            ncol= modelo. getColumnCount();
            
            for (int i=0; i< listaUsuarios.size(); i++){
            
                fila=new Object[ncol];
                fila[0]=listaUsuarios.get(i).getNombre1U();
                fila[1]=listaUsuarios.get(i).getNombre2U();
                fila[2]=listaUsuarios.get(i).getApellido1U();
                fila[3]=listaUsuarios.get(i).getApellido2U();
                fila[4]=listaUsuarios.get(i).getFotodePerfil();
                fila[5]=listaUsuarios.get(i).getCorreoU();
                fila[6]=listaUsuarios.get(i).getContraseñaU();
                fila[7]=listaUsuarios.get(i).getEstadoBloqueo();
                fila[8]=listaUsuarios.get(i).getIdRolf();
                modelo.addRow(fila);
            
           // }
 
        }
      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String busqueda= jTextField1.getText();
        ControlUsuario objcu= new ControlUsuario();
        int ncol;
        Object[] fila;
        
       // if (busqueda.equals("")){
            listaUsuarios = objcu.consultarUsuarios(busqueda);
            
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable2.setModel(modelo);
            
            modelo.addColumn("primer nombre");
            modelo.addColumn("segundo nombre");
            modelo.addColumn("primer apellido");
            modelo.addColumn("segundo apellido");
            modelo.addColumn("foto perfil");
            modelo.addColumn("correo");
            modelo.addColumn("contraseña");
            modelo.addColumn("Estado bloqueo");
            modelo.addColumn("rol");
            ncol= modelo. getColumnCount();
            
            for (int i=0; i< listaUsuarios.size(); i++){
            
                fila=new Object[ncol];
                fila[0]=listaUsuarios.get(i).getNombre1U();
                fila[1]=listaUsuarios.get(i).getNombre2U();
                fila[2]=listaUsuarios.get(i).getApellido1U();
                fila[3]=listaUsuarios.get(i).getApellido2U();
                fila[4]=listaUsuarios.get(i).getFotousuario();
                fila[5]=listaUsuarios.get(i).getCorreoU();
                fila[6]=listaUsuarios.get(i).getContraseñaU();
                fila[7]=listaUsuarios.get(i).getEstadoBloqueo();
                fila[8]=listaUsuarios.get(i).getIdRolf();
                modelo.addRow(fila);
                
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuarioC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuarioC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
