/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlCategoria;
import control.ControlLike;
import control.ControlPost;
import control.ControlUsuario;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.categoria;
import modelo.like;
import modelo.post;
import modelo.usuario;
import static vista.Login.correoglobal;

/**
 *
 * @author natal
 */
public class VistaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form VistaCategorias
     */
    LinkedList<like> listalikes;
    LinkedList<post> listaposts;
    LinkedList<categoria> listacategoria;
    LinkedList<usuario> listausuarios;
    LinkedList<like> listausuarioDarLike;//esta lista será para evaluar al usuario que dió like
    int i2 = 0;
    int j = 0;
    int k = 0;
    int contadorlike = 0;
    boolean llegada = false;
    String categoriacmb = " ";

    public VistaCategoria() {
        initComponents();
        listacategoria = new LinkedList<>();
        listaposts = new LinkedList<>();
        listalikes = new LinkedList<>();

        verpost();
        verLike2();
        consultalikeBoton2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbcategorias = new javax.swing.JComboBox<>();
        labelcorreo1 = new javax.swing.JLabel();
        labelLikes1 = new javax.swing.JLabel();
        labelLike1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion1 = new javax.swing.JTextArea();
        labeletiqueta1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btnlike1 = new javax.swing.JButton();
        btnfav1 = new javax.swing.JButton();
        btnvercomentarios1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnsiguiente1 = new javax.swing.JButton();
        btnant1 = new javax.swing.JButton();
        labelimage1 = new javax.swing.JLabel();
        btncategoria1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Categorias");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elegir Categoria");

        cmbcategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcategoriasItemStateChanged(evt);
            }
        });
        cmbcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcategoriasActionPerformed(evt);
            }
        });

        labelcorreo1.setForeground(new java.awt.Color(102, 102, 255));
        labelcorreo1.setText("jLabel1");

        labelLikes1.setText("likes");

        labelLike1.setText("jLabel3");

        txtdescripcion1.setEditable(false);
        txtdescripcion1.setColumns(20);
        txtdescripcion1.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion1);

        labeletiqueta1.setText("jLabel2");

        jLabel31.setText("Etiqueta:");

        jLabel41.setText("Categoria:");

        btnlike1.setText("Me gusta");
        btnlike1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlike1ActionPerformed(evt);
            }
        });

        btnfav1.setText("Favoritos");

        btnvercomentarios1.setText("Ver comentarios");

        btnsiguiente1.setText("Siguiente");
        btnsiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente1ActionPerformed(evt);
            }
        });

        btnant1.setText("Anterior");
        btnant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnant1ActionPerformed(evt);
            }
        });

        btncategoria1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btncategoria1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(labelimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)))
                .addGap(85, 85, 85))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(labelcorreo1)
                                            .addGap(299, 299, 299)
                                            .addComponent(labelLikes1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelLike1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel41)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel31)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(labeletiqueta1))))))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btnlike1)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnfav1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                                    .addComponent(btnvercomentarios1))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(320, 320, 320)
                            .addComponent(btnant1)
                            .addGap(18, 18, 18)
                            .addComponent(btnsiguiente1)))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(btncategoria1)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(485, 485, 485)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelcorreo1)
                        .addComponent(labelLikes1)
                        .addComponent(labelLike1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(labeletiqueta1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel41)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnvercomentarios1)
                        .addComponent(btnlike1)
                        .addComponent(btnfav1))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnant1)
                        .addComponent(btnsiguiente1))
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoriasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbcategoriasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      ControlCategoria objcc = new ControlCategoria();
        listacategoria = objcc.consultarCategoria();
        for (int j = 0; j < listacategoria.size(); j++) {
            categoria objcategoria = listacategoria.get(j);
            cmbcategorias.addItem(objcategoria.getTipoCategoria());
        }


    }//GEN-LAST:event_formWindowOpened

    private void btnlike1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlike1ActionPerformed
        // TODO add your handling code here:
        ControlLike cl = new ControlLike();

        if (llegada == false) {

            like nuevolike = new like(listaposts.get(i2).getIdpost(), "123");
            cl.insertarLike(nuevolike);

            // btnlike.setText("Me gusta");
        } else if (llegada == true) {

            like nuevolike = new like(listaposts.get(i2).getIdpost(), "123");
            cl.BorrarLikes(nuevolike);

        }
        consultalikeBoton2();
        verLike2();

    }//GEN-LAST:event_btnlike1ActionPerformed

    private void btnsiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente1ActionPerformed
        // TODO add your handling code here:

        System.err.println("CATEGORIA: " + categoriacmb);
        if ((i2 <= listaposts.size()) && i2 >= 0) {
            if (i2 == (listaposts.size() - 1)) {
                JOptionPane.showMessageDialog(rootPane, "Actualice su feed");
            } else {
                i2++;
                verpost2();
                verLike2();
                consultalikeBoton2();

            }

        }
      System.out.println(i2);
    }//GEN-LAST:event_btnsiguiente1ActionPerformed

    private void btnant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnant1ActionPerformed
        // TODO add your handling code here:

        if ((i2 <= listaposts.size()) && i2 >= 0) {
            if (i2 == 0) {
                JOptionPane.showMessageDialog(rootPane, "No hay más contenido");
            } else {
                i2--;
                verpost2();
                verLike2();
                consultalikeBoton2();
            }

        }
      System.out.println(i2);
    }//GEN-LAST:event_btnant1ActionPerformed

    private void cmbcategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcategoriasItemStateChanged
        // TODO add your handling code here:
        i2 = 0;
       verpost2();
    }//GEN-LAST:event_cmbcategoriasItemStateChanged

    public void consultalikeBoton2() {
        System.err.println("Entré al metodo");
        ControlUsuario cu = new ControlUsuario();
        listausuarios = cu.consultarUsuarios("123");//esta lista va a consultar solo la id de mi login
        ControlLike cl = new ControlLike();
        listausuarioDarLike = cl.consultarLikes();
        for (int u = 0; u < listausuarios.size(); u++) {

            llegada = cl.consultarLikesPorUsuario(listaposts.get(i2).getIdpost(), listausuarios.get(u).getCorreoU());

            if (llegada == true) {
                btnlike1.setText("No Me gusta");

                System.out.println(llegada);
                break;
            } else {
                btnlike1.setText("Me gusta");

                System.err.println(llegada);
                break;
            }

        }

    }

    private void verpost() {
        try {
            ControlPost cp = new ControlPost();
            listaposts = cp.consultarPosts();
            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i2).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i2).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i2).getDescripcion());

            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i2).getIdCategoriastf()) {
                    int categorias = listaposts.get(i2).getIdCategoriastf();
                    btncategoria1.setText(listacategoria.get(j).getTipoCategoria());

                }

            }
            labelcorreo1.setText(listaposts.get(i2).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verpost2() {
        try {

            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
                          categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            ControlPost cp = new ControlPost();
            listaposts = cp.BusquedaPosts2(categoriacmb);
            System.out.println("CATEGORIA INICIAL " + cmbcategorias.getSelectedItem());
            System.out.print(listacategoria);

            
            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i2).getIdCategoriastf()) {
                    int categorias = listaposts.get(i2).getIdCategoriastf();
                    btncategoria1.setText(listacategoria.get(j).getTipoCategoria());
      
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i2).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i2).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i2).getDescripcion());

                }

            }
            labelcorreo1.setText(listaposts.get(i2).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verLike2() {

        ControlLike objcl = new ControlLike();
        listalikes = objcl.consultarLikes();

        int cantlikes = objcl.consultarCantidadLikes(listaposts.get(i2).getIdpost());
        labelLike1.setText(String.valueOf(cantlikes));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnant1;
    private javax.swing.JButton btncategoria1;
    private javax.swing.JButton btnfav1;
    private javax.swing.JButton btnlike1;
    private javax.swing.JButton btnsiguiente1;
    private javax.swing.JButton btnvercomentarios1;
    private javax.swing.JComboBox<String> cmbcategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelLike1;
    private javax.swing.JLabel labelLikes1;
    private javax.swing.JLabel labelcorreo1;
    private javax.swing.JLabel labeletiqueta1;
    private javax.swing.JLabel labelimage1;
    private javax.swing.JTextArea txtdescripcion1;
    // End of variables declaration//GEN-END:variables
}
